### ISSUE TITLE
Error: getaddrinfo ENOTFOUND iZ94st1428jZ iZ94st1428jZ:4150

### ISSUE THREAD

**Issue by zanjs** [dudleycarr/nsqjs#91]
### curl ok

```
$ curl -d "ssssgfsadfgsdfsdfsfgddsf"  "http://120.24.210.90:4151/put?topic=test"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    26  100     2  100    24     25    307 --:--:-- --:--:-- --:--:--   307OK

```

### run error
```ssh
$ node .
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND iZ94st1428jZ iZ94st1428jZ:4150
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

### code 

```
var nsq = require('nsqjs');
var reader = new nsq.Reader('topic', 'test', {
  lookupdHTTPAddresses: '120.24.210.90:4161'
});

reader.connect();

reader.on('message', function (msg) {
  console.log('Received message [%s]: %s', msg.id, msg.body.toString());
  msg.finish();
});

```

**Comment by dudleycarr** [comment]
Are you sure you're running `nsqlookupd`?

**Comment by janbaer** [comment]
I've actually the same problem while trying nsqjs. Writing works but when trying to read, the error will be thrown. I'm running the whole NSQ stack with docker-compose and the port 4161 is of course exposed.

So ```curl http://localhost:4161/topics``` is working without any errors. Any ideas?

**Comment by dudleycarr** [comment]
Can you share your docker-compose.yaml and how your configuring nsqjs?

**Comment by janbaer** [comment]
That's my docker-compose.yml

```
version: '3'
services:
  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    depends_on:
      - nsqlookupd  
    ports:
      - "4171:4171"
```

And that's the code from the nqjs Readme page on Github.

```
const nsq = require('nsqjs')

const reader = new nsq.Reader('sample_topic', 'test_channel', {
  lookupdHTTPAddresses: '127.0.0.1:4161'
})

reader.connect()

reader.on('message', msg => {
  console.log('Received message [%s]: %s', msg.id, msg.body.toString())
  msg.finish()
})
```

The error happens first after I wrote the first message to the topic.
